# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1133e5c486d3d11bd4704e41cc4c458325625c7dbe6a7323509069700cff53360b70a22b4f7343142f5e8a359d3857b1e8b8581c8124d05f6d641fcf2816124b

test:
  secret_key_base: a21ccbe0ed477cce81353106b0c639a67b6a30c940dfc9a06aa1859613c760f1d600b82d633a924c3e65aae26647460ee3983177787b3367211b0b78e8eb40e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
